### ISSUE TITLE
1.12 - Crafting recipe for graphite doesn't work

### ISSUE THREAD

**Issue by ExDomino** [ZeroNoRyouki/BigReactors#118]
Hello, in the 1.12 version, the recipe for the graphite doesn't work. We can enable smeltings coal for graphite, but the crafting recipe, even to true, doesnt work.
The setting "registerGraphiteCoalCraftingRecipes=true" doesn't work.

Minecraft 1.12;
Forge 14.21.1.2405;
Extrême Reactors : 0.4.5.33.

**Comment by ZeroNoRyouki** [comment]
Fixed in the next release

**Comment by MauveCloud** [comment]
Please reopen.  I'm using Minecraft 1.12, Forge 14.23.1.2604, and Extreme Reactors 0.4.5.45, and this still doesn't work (and before you ask, yes I have relaunched Minecraft since changing the settings).  The only recipes I find in JEI for making the graphite ingot are for getting it back from the block or smelting the dust (which don't help if I can't make the ingot some other way first).

**Comment by ZeroNoRyouki** [comment]
what you get when you try to:

- smelt coal
- smelt charcoal
- craft gravel-coal-gravel in the top row of the crafting grid
- craft gravel-charcoal-grave in the top row of the crafting grid

?l

**Comment by MauveCloud** [comment]
Smelt coal/charcoal: no output (desired behavior, since I have turned off this option in the config (to prevent unintentional smelting of coal/charcoal via shift+click), and I have to place the coal/charcoal in the furnace top slot manually to even try)
Craft gravel-coal-gravel or gravel-charcoal-gravel in the top row of the crafting rid: no output (unexpected result, since I turned on the options for the crafting recipes in the config)

As a temporary workaround, I have made a CraftTweaker script to allow smelting ore:dustCoal or ore:dustCharcoal into graphite ingots, but I'd prefer to use the config-triggered gravel-(char)coal-gravel recipes.

**Comment by ZeroNoRyouki** [comment]
I've found the problem and fixed it. The fix will be included in the next release
